name: API Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Set up JDK 21
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven' # Caches Maven dependencies

      # Cache Maven dependencies to improve speed
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          mvn clean install
          mvn test

      # Archive test results (HTML report from test-output folder)
      - name: Archive test reports
        if: always() # Ensures artifacts are saved even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-output/
